---
abstract: 'Plugin that adds XMLHttpRequest detection to CGI::Application'
author:
  - 'Jiří Pavlovský  <jira@getnet.cz>'
build_requires:
  Test::More: 0
configure_requires:
  Module::Build: 0.36
generated_by: 'Module::Build version 0.3607'
license: perl
meta-spec:
  url: http://module-build.sourceforge.net/META-spec-v1.4.html
  version: 1.4
name: CGI-Application-Plugin-DetectAjax
provides:
  CGI::Application::Plugin::DetectAjax:
    file: lib/CGI/Application/Plugin/DetectAjax.pm
    version: 0.04
requires:
  CGI::Application: 0
resources:
  license: http://dev.perl.org/licenses/
version: 0.04
